### ISSUE TITLE
Script is flawless..

### ISSUE THREAD

**Issue by chloe27anne** [jacktripperz/bnbcropsfarmer#1]
Hi just want to say the script is 100 percent working and flawless..
Just a question though, will this work also on BUSD cropsfarmer?

**Comment by jacktripperz** [comment]
Hi Chloe, I'm glad to hear that! Thanks for the feedback!
It depends on how the BUSD contract looks. You will have to change the contract address defined in the variable "dm_contract_addr" in line 9 of "farmer.py" and run the script to see if it works.
If the BNB and rhe BUSD contracts are the same then it will work by just doing the above.

**Comment by chloe27anne** [comment]
Got it thank you. :)
